### ISSUE TITLE
细节优化建议

### ISSUE THREAD

**Issue by Fzoss** [quick123official/quick_redis_blog#1]
目前该应用在表示key已经不存在的提示确实有点不够醒目,而且在debug手动查阅记录的时候容易多次点开一个已经不存在的key导致浪费时间,
如果键过期后手动点击触发查询找不到的时候,可以在列表标记x等类似的符号表示该key已经不存在就更好了
另外就是建议增加keys列表自动或手动刷新功能,尝试使用了一会儿没有找到刷新的方法,似乎只能关闭连接后重新打开
如果能顺便提供一个增删对比的功能就好了,比如点击检查按钮后消失的键标红,新增标绿

**Comment by quick123official** [comment]
1. key已经不存在的提示确实有点不够醒目（这个我想下改进方法）
2. keys列表自动或手动刷新功能（点击输入keys的搜索按钮，可以刷新）
感谢你的建议！
