### ISSUE TITLE
scan TypeError: this.resolveResult is not a function

### ISSUE THREAD

**Issue by lisy5** [quick123official/quick_redis_blog#10]
命令行scan报错“this.resolveResult is not a function”

> scan 0 match 2020*
TypeError: this.resolveResult is not a function
> scan 0
TypeError: this.resolveResult is not a function

**Comment by quick123official** [comment]
确定是一个BUG，周末研究一下。

**Comment by quick123official** [comment]
请关注后续的 2.3.0 版本

**Comment by itMuYou** [comment]
命令行 xinfo 也会报这个错

**Comment by itMuYou** [comment]
用的2.3.1版本

**Comment by quick123official** [comment]
> 用的2.3.1版本



> 命令行 xinfo 也会报这个错

还不支持 xinfo 命令行哈。貌似 5.x 才有这个命令吧
