### ISSUE TITLE
报错：loadRedisKeysByPattern errorReplyError: ERR keys is disabled command

### ISSUE THREAD

**Issue by zhao1-1** [quick123official/quick_redis_blog#104]
操作系统
Mac

QuickRedis 版本
例子：2.6.0

问题描述
连接成功后，报错：loadRedisKeysByPattern errorReplyError: ERR keys is disabled command。请问咋回事？

**Comment by quick123official** [comment]
这个问题的本质是redis服务器禁用了keys。麻烦升级到2.7.1版本，2.7.1版本把keys命令改为scan命令。
