### ISSUE TITLE
quickredis 两万的数据限制

### ISSUE THREAD

**Issue by 2247304904** [quick123official/quick_redis_blog#109]
操作系统
Windows

QuickRedis 版本
例子：2.7.1

问题描述
官方大大 什么时候可以更新这个两万条的上限啊
![image](https://user-images.githubusercontent.com/45359235/179930459-c4eea85b-5507-4b8d-917f-ed7c0ab46fcf.png)

**Comment by quick123official** [comment]
太大的话，很卡的哦。加一个自己配置数据条数的功能？
