### ISSUE TITLE
很喜欢你做的产品,请问下经常连接超时,还有搜索key,只有模糊搜索?有匹配搜索么

### ISSUE THREAD

**Issue by icecreamtohot** [quick123official/quick_redis_blog#11]
很喜欢你做的产品,请问下经常连接超时,还有搜索key,只有模糊搜索?有匹配搜索么

**Comment by quick123official** [comment]
1. “请问下经常连接超时”，现象是什么，请提供一下截图。
2. 已经同时支持模糊搜索和匹配搜索。当key完全匹配时，这个key会出现在列表中的第一个。

**Comment by litao09h** [comment]
> 1. “请问下经常连接超时”，现象是什么，请提供一下截图。
> 2. 已经同时支持模糊搜索和匹配搜索。当key完全匹配时，这个key会出现在列表中的第一个。

我们公司不支持keys命令，能用scan搜索么，或者支持精确查找？ 
```
ReplyError: ERR unknown command `keys`, with args beginning with: `tag`,
```

**Comment by quick123official** [comment]
scan 不支持模糊匹配的
