### ISSUE TITLE
请问数据是实时刷新的么

### ISSUE THREAD

**Issue by xingjunant** [quick123official/quick_redis_blog#12]
请问数据是实时刷新的么, 可否在界面上提供一个刷新按钮?
另外Map结构中偶尔出现相同key的两个键值对

**Comment by quick123official** [comment]
1. 自动实时刷新，不太合理。原因是redis的可以有一定的随机性，刷新之后，可能左边的列表key不见了；
2. 点击界面上搜索按钮，实际上效果就等于刷新按钮；
3. “另外Map结构中偶尔出现相同key的两个键值对”，这个问题，麻烦提供一下截图哈！

**Comment by xingjunant** [comment]
![微信图片_20201019100501](https://user-images.githubusercontent.com/10667357/96393733-9ab14a00-11f2-11eb-8b90-efe167598b8a.png)
复现方法是先选中一条map类型的数据, 然后双击左边的连接名

**Comment by quick123official** [comment]
现在上班，我晚上回去研究下~我不是全职搞这个工具，所以不一定那么快解决哈

**Comment by xingjunant** [comment]
嗯嗯, 有刷新用就行, 这个小问题不影响使用
