### ISSUE TITLE
UI界面优化

### ISSUE THREAD

**Issue by zhanghzong** [quick123official/quick_redis_blog#14]
1、支持批量删除或者一键 [fluashdb]
2、根据 key 名称 冒号 已树状形式展示。如图

![image](https://user-images.githubusercontent.com/4384876/97797159-b9352d80-1c55-11eb-8a7a-6783274e5f0d.png)

**Comment by quick123official** [comment]
请关注后续的2.3.0版本。2.3.0会增加目录显示keys，像RDM那样。

**Comment by zhanghzong** [comment]
2.3.0 版本使用下来, 与之前的版本没有任何变化呀

![image](https://user-images.githubusercontent.com/4384876/117388175-d0164e80-af1c-11eb-9893-1ad7d091a8c3.png)

**Comment by quick123official** [comment]
新增功能 - 使用目录显示和操作keys
启用该功能的方法：主菜单 -> 文件 -> 系统设置 -> 设置分隔符

**Comment by zhanghzong** [comment]
> 新增功能 - 使用目录显示和操作keys
> 启用该功能的方法：主菜单 -> 文件 -> 系统设置 -> 设置分隔符

谢谢, 可以了
