### ISSUE TITLE
REDIS 重连之后，界面提示 Error: Connection is closed.

### ISSUE THREAD

**Issue by buxiuzhang** [quick123official/quick_redis_blog#15]
redis 服务器关闭后，然后进行重新启动。
QuickReids 左边的目录也提示连接成功 "连接建立成功"。
但是右边的桌面依旧提示 “Error: Connection is closed.”
需要重新打开一个窗口，才能进行操作》
希望你们开发时注意一下这个问题，这个bug 还是很明显的。
也许你们发现了，具体为啥不修复或许有其他问题吧。

具体测试方式 启动redis服务器-> 使用QuickRedis 连接，打开一个桌面进行操作->然后关闭redis服务器，然后再重新启动->使用QuickRedis 进行操作。这时会便会提示“Error: Connection is closed.”。
需要重新打开一个桌面才行

**Comment by quick123official** [comment]
这种情况，重新连接吧。不太好解决

**Comment by quick123official** [comment]
这种情况，重新连接吧。不太好解决
