### ISSUE TITLE
请问，是否支持ssh呢？

### ISSUE THREAD

**Issue by allesx** [quick123official/quick_redis_blog#16]
偶然发现了这个工具，感觉特别好，请问是否支持ssh呢？

**Comment by quick123official** [comment]
你会考虑提交一个 pull reqeust 支持这个功能吗？:)

**Comment by xiuluodaren** [comment]
发现一个ssh库 https://github.com/mscdex/ssh2#channel 感觉应该是可行的,目前正在研究.

**Comment by xiuluodaren** [comment]
我放弃了....

**Comment by xiuluodaren** [comment]
https://github.com/x2jia/medis/  发现了另一个开源项目,也是用Electron, React, node做的,正在考虑能不能抄过来......

**Comment by xiuluodaren** [comment]
> 
> 
> 你会考虑提交一个 pull reqeust 支持这个功能吗？:)

我在gitee提交了一个pull request,请处理.

**Comment by zhoudian2010** [comment]
> > 你会考虑提交一个 pull reqeust 支持这个功能吗？:)
> 
> 我在gitee提交了一个pull request,请处理.

修罗，麻烦提交到github。感谢！希望你成为QuickRedis的开发者。

**Comment by xiuluodaren** [comment]
> 
> 
> 偶然发现了这个工具，感觉特别好，请问是否支持ssh呢？

已经实现了,自行编译打包即可.

**Comment by quick123official** [comment]
> > 偶然发现了这个工具，感觉特别好，请问是否支持ssh呢？
> 
> 已经实现了,自行编译打包即可.

请加一个微信。发你的微信号到我的邮箱：harryzhou6@163.com

**Comment by xiuluodaren** [comment]
> > > 偶然发现了这个工具，感觉特别好，请问是否支持ssh呢？
> > 
> > 
> > 已经实现了,自行编译打包即可.
> 
> 请加一个微信。发你的微信号到我的邮箱：[harryzhou6@163.com](mailto:harryzhou6@163.com)

xiuluodarendeweixin

**Comment by quick123official** [comment]
2.2.0 版本支持了ssh
