### ISSUE TITLE
"Melihat" labels on English

### ISSUE THREAD

**Issue by toryano0820** [quick123official/quick_redis_blog#17]

**Comment by quick123official** [comment]
Sorry! I don't understand what you mean.

**Comment by toryano0820** [comment]
![image](https://user-images.githubusercontent.com/11425804/99207889-1f938180-27fa-11eb-8232-9edcc8bd4638.png)

If you did it on purpose, then no worries at all. :)

**Comment by quick123official** [comment]
I get it. Thank you very much! We will fix this problem as soon as possible.

**Comment by quick123official** [comment]
Would you consider submitting a pull request? haha..

**Comment by quick123official** [comment]
What languages ​​are commonly used in the Philippines?

**Comment by toryano0820** [comment]
> What languages ​​are commonly used in the Philippines?

English (en-US) if you are pertaining to software ^^"

**Comment by toryano0820** [comment]
I created a pull request as you suggested earlier ^^"
https://github.com/quick123official/quick_redis_blog/pull/18

**Comment by quick123official** [comment]
> I created a pull request as you suggested earlier ^^"
> #18

Thanks!

**Comment by quick123official** [comment]
> > What languages ​​are commonly used in the Philippines?
> 
> English (en-US) if you are pertaining to software ^^"

Does the Philippines have its own unified language?

**Comment by toryano0820** [comment]
> Does the Philippines have its own unified language?

Yeah, our native language is Filipino (fil-PH)

**Comment by quick123official** [comment]
> > Does the Philippines have its own unified language?
> 
> Yeah, our native language is Filipino (fil-PH)

Would you consider adding Filipino (fil-PH)? :)

**Comment by toryano0820** [comment]
> Would you consider adding Filipino (fil-PH)? :)

It is not necessary since I am pretty sure everyone that will use this tool from Philippines knows English :)
Another reason is that it is not normal for us to see Software with Filipino language, if so, that would be harder to use ^^"

**Comment by quick123official** [comment]
> > Would you consider adding Filipino (fil-PH)? :)
> 
> It is not necessary since I am pretty sure everyone that will use this tool from Philippines knows English :)
> Another reason is that it is not normal for us to see Software with Filipino language, if so, that would be harder to use ^^"

Thank you so much for your suggestion! Congratulations on becoming a developer of quickredis! hah

**Comment by quick123official** [comment]
> > Would you consider adding Filipino (fil-PH)? :)
> 
> It is not necessary since I am pretty sure everyone that will use this tool from Philippines knows English :)
> Another reason is that it is not normal for us to see Software with Filipino language, if so, that would be harder to use ^^"

What are the commonly used online communication tools in the Philippines？Facebook or WhatsApp?

**Comment by toryano0820** [comment]
> What are the commonly used online communication tools in the Philippines？Facebook or WhatsApp?

Facebook

**Comment by malcolmsearle** [comment]
Nice app, but along with the Melihat menu in the English version there's also a Melihat button to view elements with!

![2020-11-23 09_10_28-Clipboard](https://user-images.githubusercontent.com/60131984/99940157-eb750f00-2d6b-11eb-8e68-a606f9787959.png)

**Comment by quick123official** [comment]
fixed in2.2.0
