### ISSUE TITLE
集群链接直接报错

### ISSUE THREAD

**Issue by victPang** [quick123official/quick_redis_blog#2]
正常填写数据。。。请问这是啥情况
ClusterAllFailedError: Failed to refresh slots cache
虽然很感谢您的开源，但忘能经得住基本考验

**Comment by quick123official** [comment]
It is likely that you are not connected to the redis cluster. Please try to use "直连" mode. 
-------
很可能你尝试连接的redis不是集群模式，请尝试使用 “直连” 模式。

**Comment by quick123official** [comment]
很可能你尝试连接的redis不是集群模式，请尝试使用 “直连” 模式。

**Comment by quick123official** [comment]
使用 redis-cli 连接上你的集群，先保证当前环境能连接上集群。

**Comment by quick123official** [comment]
已经解决，请关注 1.0.6 版本！多谢提bug哈！
