### ISSUE TITLE
批量操作

### ISSUE THREAD

**Issue by TANZAME** [quick123official/quick_redis_blog#22]
急需 key 的批量删除。。。一个一个点删除，好蠢。。。

**Comment by quick123official** [comment]
最近工作太忙了。后续想考虑弄一个树结构展示和操作。

**Comment by TANZAME** [comment]
作者好人，有 ctrl 键多选，类似的 windows的多选操作就更好了：）

**Comment by w935903854** [comment]
对的  就差一个批量删除  一个个点 真的是太累了

**Comment by w935903854** [comment]
作者作者  急需一个批量删除key 的操作

**Comment by wyx666518** [comment]
跪求批量删除。。。

**Comment by quick123official** [comment]
请关注后续的2.3.0版本。2.3.0会增加目录显示keys，像RDM那样。
