### ISSUE TITLE
redis的key可以最多显示10000条

### ISSUE THREAD

**Issue by lbx335214** [quick123official/quick_redis_blog#23]
redis的key可以最多显示10000条？

**Comment by quick123official** [comment]
可以显示无限条数据

**Comment by quick123official** [comment]
后续修改一下

**Comment by quick123official** [comment]
不至10000条，理论上可以显示无限条记录。
<img src="https://quick123.net/images/temp/10000-record.png"></img>

**Comment by quick123official** [comment]
是的，最多10000条。显示太多，意义也不大。使用搜索功能，把想要的key搜索出来就行。
