### ISSUE TITLE
集群模式连接报错

### ISSUE THREAD

**Issue by leohapps** [quick123official/quick_redis_blog#3]
发生错误。ClusterAllFailedError: Failed to refresh slots cache.

**Comment by quick123official** [comment]
1. 确保本地能连接上你的集群环境，使用命令：redis-cli -h 你的IP -p  你的端口 -c
2. 下载最新的版本进行连接，目前最新的版本是 QuickRedis-1.0.7。

**Comment by quick123official** [comment]
无反馈
