### ISSUE TITLE
大数据量查看有性能问题，直接 OOM

### ISSUE THREAD

**Issue by Lizhooh** [quick123official/quick_redis_blog#32]
查看一个 string，放了 200 多 M 的数据，就 OOM 了。

**Comment by Lizhooh** [comment]
![QQ拼音截图20210420140309](https://user-images.githubusercontent.com/19299088/115345360-460e7c00-a1e1-11eb-956b-af6a97183eec.png)

**Comment by Lizhooh** [comment]
不止大数据量的问题，有时候放着没动，突然就蹦了，怀疑有内存泄露。

**Comment by quick123official** [comment]
我们看下如何重现这个问题

**Comment by quick123official** [comment]
“一个 string，放了 200 多 M 的数据” 感觉这样使用redis，不太合理哈。不动的原因是网络io太慢了，界面就卡在哪里。
