### ISSUE TITLE
首页展示所有key和过滤框筛选key的问题

### ISSUE THREAD

**Issue by Carbin007** [quick123official/quick_redis_blog#33]
首页展示所有key的时候，应该使用了keys*命令，但是很多时候生产或者测试环境是禁用了keys命令的，所以直接报错了，没有刷新，并且当redis内部key的数量很多时，keys命令是非常危险的，建议改成scan命令去展示

**Comment by quick123official** [comment]
2.3.0 版本将会去掉keys命令改为scan。不过条数依然限制在10000条。另外2.3.0会增加目录显示keys，像RDM那样，这种模式下会使用keys命令。
