### ISSUE TITLE
内容部分显示空间太小了

### ISSUE THREAD

**Issue by oldyoungman** [quick123official/quick_redis_blog#38]
连接、目录树占了一般的屏幕，建议优化一下窗口显示布局

**Comment by shakeyo** [comment]
赞同，只有16个属性还要分页不太合理
小小建议，感谢付出

**Comment by quick123official** [comment]
目前这个布局符合我个人需求。后续看看有没有时间，加一个记忆的功能。这样应该能满足你们的需求。
