### ISSUE TITLE
可以支持linux吗？

### ISSUE THREAD

**Issue by KANLON** [quick123official/quick_redis_blog#4]

**Comment by quick123official** [comment]
我们在下一个版本考虑支持linux。另外，请给我们一个star哈

**Comment by KANLON** [comment]
> 我们在下一个版本考虑支持linux。另外，请给我们一个star哈

请问这个是大概是时候支持呢？你们下一版版本是什么时候呢？

**Comment by zhoudian2010** [comment]
大概需要两周的时间。如果期望尽快出版本，请留下邮箱。我先发一个内侧版本给你试用下。

**Comment by quick123official** [comment]
大概需要两周的时间。如果期望尽快出版本，请留下邮箱。我先发一个内侧版本给你试用下。

**Comment by KANLON** [comment]
不用了，麻烦了，突然发现你们好像没开源源代码，担心有点不太安全

**Comment by quick123official** [comment]
我们目前没有开源计划呢。360 和 金山毒霸 把我们放在沙箱24小时监控，其实可以放心使用的。

**Comment by quick123official** [comment]
打了一个linux版本，看下行不行。 QuickRedis-2.0.0-linux-x86_64.AppImage
，地址：https://github.com/quick123official/quick_redis_blog/releases
