### ISSUE TITLE
有刷新功能么？没有能否添加一个？

### ISSUE THREAD

**Issue by lxjmaster** [quick123official/quick_redis_blog#41]
就是一个库当中的key有修改（如增删），没有刷新功能，重新加载（CTRL+R）会重载整个界面，而不是在一打开的库当中重载。所以能否在库当中刷新当前key的功能

**Comment by quick123official** [comment]
新增、删除应该都是自动刷新的。如果没有刷新，点击key搜索的放大镜也可以。

**Comment by lxjmaster** [comment]
@quick123official 
> 新增、删除应该都是自动刷新的。如果没有刷新，点击key搜索的放大镜也可以。

首先抱歉，前面没说清楚，前面说的增删是代码下面的增删，软件中增删会自动刷新。然后点击key搜索的放大镜可以刷新了，不过个人感觉不够明显，像我这种第一次用的可能会不知道，建议大佬做的明显一点，或者加个说明。最后感谢大佬的回复。

**Comment by quick123official** [comment]
“代码下面的增删”自动刷新，需要定期刷新key，这个实现不太好。自己点击一下key搜索的放大镜吧。后面我们看下要不要加一个明显的提示。
