### ISSUE TITLE
使用过程中遇到bug，进程崩溃

### ISSUE THREAD

**Issue by lxjmaster** [quick123official/quick_redis_blog#43]
渲染器进程崩溃，没做任何操作
![6@MKCAF4Y_{KDM7GONG`4EX](https://user-images.githubusercontent.com/23435172/122637710-c9394900-d122-11eb-834e-37d574088859.png)
日志
[info.log](https://github.com/quick123official/quick_redis_blog/files/6680405/info.log)

**Comment by quick123official** [comment]
日志里面没有看出是啥问题。先升级到最新的2.3.0版本试下。有问题再报issue过来。
