### ISSUE TITLE
geopos 命令无法使用

### ISSUE THREAD

**Issue by Windy-Rain** [quick123official/quick_redis_blog#44]

**Comment by Windy-Rain** [comment]
![image](https://user-images.githubusercontent.com/50687293/125914927-70499893-9f43-42df-8956-f423d8f581d4.png)

**Comment by Windy-Rain** [comment]
![image](https://user-images.githubusercontent.com/50687293/125916678-b80e365e-11d8-4420-99a3-f581691e0fad.png)

**Comment by Windy-Rain** [comment]
命令大写会无法识别
![image](https://user-images.githubusercontent.com/50687293/125917661-fdabdbed-efd6-418a-99fe-67cd1f4d7c42.png)

**Comment by quick123official** [comment]
已经修复。关注 v2.4.0 版本。
