### ISSUE TITLE
key查询太慢，建议支持类似keys命令的模式匹配查询

### ISSUE THREAD

**Issue by mrbeardad** [quick123official/quick_redis_blog#47]
![image](https://user-images.githubusercontent.com/54128430/129158783-b622d46d-b46a-4c07-a8f1-e11a14b6c2d5.png)

如果能支持keys命令的模式匹配的话，使用`PowerStrategyResult*`会比`PowerStrategyResult`查询快非常非常多

**Comment by quick123official** [comment]
某些运维禁止使用 keys 命令，所以我们改为 scan 了。

**Comment by quick123official** [comment]
SCAN 的数量减少，体验好了很多。关注下一个版本
