### ISSUE TITLE
当redis集群中key的数量达到百万时，非常慢

### ISSUE THREAD

**Issue by hexufeng** [quick123official/quick_redis_blog#49]
查看key或者任何读操作都会卡半天

**Comment by quick123official** [comment]
本地连接远程redis，慢的原因是网络的延迟。这个没有办法解决。

**Comment by quick123official** [comment]
kisyki 网站是自研的吗？哈哈

**Comment by quick123official** [comment]
![image](https://user-images.githubusercontent.com/58046636/135638330-9f6afda6-2b47-466a-a2e4-e76987ea8642.png)
选择非目录现实的方式，会变得很快

**Comment by hexufeng** [comment]
> kisyki 网站是自研的吗？哈哈

我草，之前的个人技术博客，域名没续费被恶意利用了。。。

**Comment by quick123official** [comment]
目录显示会把所有key加载出来。非目录显示只会加载前1万条记录。
