### ISSUE TITLE
希望有可以多选删除的功能（并且删除后能自动刷新列表），以及json值的显示宽度无自适应

### ISSUE THREAD

**Issue by chenbihao** [quick123official/quick_redis_blog#5]
如题，有些值我想删掉，要点key然后移动鼠标到最右边的删除图标循环操作好多次

并且删除后列表还存在这个被我删除了的key，只能关掉tab再重新连才能刷新列表

以及右边的值显示框无法自适应（如果应用可以记住调整后的宽度、大小、位置那就更好了）
![image](https://user-images.githubusercontent.com/21167262/88494771-0ae07300-cfea-11ea-9bd2-1ff4a074dbb9.png)

已star，祝客户端越来越好

**Comment by quick123official** [comment]
1. 批量删除值；
2. 单个或者批量删除值后，刷新列表；
这两个功能后续的版本加上。
“右边的值显示框无法自适应”，这个问题重现不了

**Comment by quick123official** [comment]
“右边的值显示框无法自适应”重现出来了，3个问题都纳入后续版本计划。

**Comment by zhoudian2010** [comment]
这个周末的版本应该会加上这些功能。请给一个star哈！

**Comment by quick123official** [comment]
这个周末的版本应该会加上这些功能。请给一个star哈！

**Comment by quick123official** [comment]
请留意 V2.0.2 版本

**Comment by chenbihao** [comment]
“右边的值显示框无法自适应”
现在能自适应拉宽啦，但是拉窄就没自适应 ：）

**Comment by quick123official** [comment]
get

**Comment by zhoudian2010** [comment]
周末研究了一下目前使用的ui库，自适应拉窄暂时还不能支持  :(

**Comment by quick123official** [comment]
周末研究了一下目前使用的ui库，自适应拉窄暂时还不能支持 :(
