### ISSUE TITLE
Please provide screenshots.

### ISSUE THREAD

**Issue by easyu** [quick123official/quick_redis_blog#56]
Please provide screenshots.

_Originally posted by @quick123official in https://github.com/quick123official/quick_redis_blog/issues/54#issuecomment-940605491_

**Comment by easyu** [comment]
![image](https://user-images.githubusercontent.com/52410697/137652853-9e6cfae1-740c-49aa-8489-0c17544a3d43.png)

**Comment by quick123official** [comment]
重复
