### ISSUE TITLE
官网挂掉了？

### ISSUE THREAD

**Issue by yulincoder** [quick123official/quick_redis_blog#6]
如题

**Comment by quick123official** [comment]
我刚才在全国检测了一下，很多地区都能访问。QuickRedis 是面向全球的用户，官网服务器部署在香港，国内有些地方访问不排除会被墙掉。另外，麻烦给一个 start 哈！

**Comment by quick123official** [comment]
全国大部分地方访问都挺快的，看下面这个图。
![1](https://user-images.githubusercontent.com/58046636/89363156-19bdd880-d702-11ea-8e85-4394d7a9b1be.png)
