### ISSUE TITLE
cluster数据获取有问题

### ISSUE THREAD

**Issue by Sorieee** [quick123official/quick_redis_blog#61]
感觉部分数据获取不到
1. 第一次进入
![image](https://user-images.githubusercontent.com/8654292/139655019-d3870b05-4cf8-4f71-a6ee-8e7b3b906930.png)
2. 第二次进入 
![image](https://user-images.githubusercontent.com/8654292/139655052-a2f15111-2532-48c1-afd0-ef1d487f3cef.png)

3. 另外 能否提供一个刷新的按钮，刷新已打开的连接的数据

**Comment by Sorieee** [comment]
版本 2.4.1

**Comment by quick123official** [comment]
如果使用模糊查询，建议每个cluster的节点都在QuickRedis下创建一个连接

**Comment by Sorieee** [comment]
然而这样并不够人性化，我还得去找数据在cluster哪个节点。。

**Comment by quick123official** [comment]
> 然而这样并不够人性化，我还得去找数据在cluster哪个节点。。

cluster 是根据明确的key路由的，模糊查询的场景下，它也不知道去哪个node取呢。

**Comment by Sorieee** [comment]
> > 然而这样并不够人性化，我还得去找数据在cluster哪个节点。。
> 
> cluster 是根据明确的key路由的，模糊查询的场景下，它也不知道去哪个node取呢。

竞品暂时未发现类似问题。

**Comment by quick123official** [comment]
> > > 然而这样并不够人性化，我还得去找数据在cluster哪个节点。。
> > 
> > 
> > cluster 是根据明确的key路由的，模糊查询的场景下，它也不知道去哪个node取呢。
> 
> 竞品暂时未发现类似问题。

哪个工具？发来我研究一下。哈哈

**Comment by Sorieee** [comment]
RDM我记得没这个问题 不过现在不用了我。
这个应该也没有。
https://github.com/qishibo/AnotherRedisDesktopManager

**Comment by quick123official** [comment]
> RDM我记得没这个问题 不过现在不用了我。 这个应该也没有。 https://github.com/qishibo/AnotherRedisDesktopManager

AnotherRedisDesktopManager好像是可以。我研究一下哈。

**Comment by quick123official** [comment]
2.6.2版本修复这个问题

**Comment by Sorieee** [comment]
ok thx

**Comment by Sorieee** [comment]
> 2.6.2版本修复这个问题

经过实测，好像并未完全修复该问题，升级时没有卸载，直接安装的2.6.2，见gif。

![quickRedis2](https://user-images.githubusercontent.com/8654292/148055448-d759e1e4-fc87-41be-82ea-52c9bcfddbf7.gif)

**Comment by quick123official** [comment]
185 属于哪个cluster 的 node ？ 我重现不了这个问题呢

**Comment by Sorieee** [comment]
> 185 属于哪个cluster 的 node ？ 我重现不了这个问题呢

太久了 忘了

**Comment by Sorieee** [comment]
> > 185 属于哪个cluster 的 node ？ 我重现不了这个问题呢
> 
> 太久了 忘了
如果没有其他人反馈就当没有哇
