### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by jzh369** [quick123official/quick_redis_blog#68]
查看中文会乱码

**Comment by quick123official** [comment]
提供一个截图？

**Comment by jzh369** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quick123official/quick_redis_blog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月27日(星期六) 晚上11:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [quick123official/quick_redis_blog] 中文乱码 (Issue #68)





 
提供一个截图？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by quick123official** [comment]
下载2.7.0版本试试
