### ISSUE TITLE
首次链接 出现 keys * 命令

### ISSUE THREAD

**Issue by onassis-jing** [quick123official/quick_redis_blog#71]
由于执行keys命令，redis会锁定，如果数据庞大的话可能需要几秒或更长，对于生产服务器上锁定几秒这绝对是灾难了。感觉这个问题影响还是蛮大的。

**Comment by quick123official** [comment]
呀？ 我看下先

**Comment by quick123official** [comment]
![image](https://user-images.githubusercontent.com/58046636/143965260-e98aee15-ccb1-41f5-b3a6-96748c1587ba.png)
设置分隔符这里保留为空。帮忙试试哈

**Comment by onassis-jing** [comment]
> 
抓包试了下，暂时没发下有keys * 操作，已经换成scan了。建议你们抓包自己再看下。查询某个字段时候还是用的keys 操作。
如果这个key很多的话，还是会发生同样的问题。因为用了你们的工具导致我们线上出现了故障。。
![1638238099(1)](https://user-images.githubusercontent.com/7564111/143973155-5163b31d-7edc-4b66-9875-e4c9fdf86b3c.jpg)

>
