### ISSUE TITLE
双击会有重复值

### ISSUE THREAD

**Issue by LastWind523** [quick123official/quick_redis_blog#74]
单击时
![image](https://user-images.githubusercontent.com/48267930/146676304-2724bfa6-4196-4903-ae2b-37cd9c47b9d4.png)
双击时
![image](https://user-images.githubusercontent.com/48267930/146676333-a1af468c-f373-492e-958d-b0bdf0dc6acb.png)

**Comment by quick123official** [comment]
关注 2.7.1 版本哈
