### ISSUE TITLE
Key 不存在或已被删除

### ISSUE THREAD

**Issue by lyy1010e** [quick123official/quick_redis_blog#77]
![image](https://user-images.githubusercontent.com/40046583/147634535-0f43b256-f252-4a7b-8acc-d814a83d068e.png)
其实这个key是存在并且是有值的，但在客户端上无法显示
![image](https://user-images.githubusercontent.com/40046583/147634640-e36e19b8-8929-4aff-9265-fdd06760038f.png)

**Comment by quick123official** [comment]
下载2.7.0版本试试
