### ISSUE TITLE
long 类型数据显示精度问题

### ISSUE THREAD

**Issue by HanderUp** [quick123official/quick_redis_blog#78]
![image](https://user-images.githubusercontent.com/22523322/149070139-8b437208-c396-498b-bd7a-2ae4d10e2649.png)
缓存中保存数据类型为 long，查看时，由于精度问题，导致后两位显示错误

**Comment by quick123official** [comment]
前端展示json是会丢失精度的。后面我加一个json是否自动格式化json的开关。关闭json自动格式化就能正常显示了。

**Comment by quick123official** [comment]
请下载 2.6.2 版本
