### ISSUE TITLE
key列表可以支持排序么？

### ISSUE THREAD

**Issue by klarkxy** [quick123official/quick_redis_blog#79]
![image](https://user-images.githubusercontent.com/6316992/149082643-01089cd6-6ad6-4fc8-b563-eec239281f77.png)
我知道这么乱是可能是我设计的不好
但是key的列表能排序么？

**Comment by quick123official** [comment]
先排序，后渲染，会慢一点

**Comment by quick123official** [comment]
下载2.7.0版本试试
