### ISSUE TITLE
关于db数据刷新问题

### ISSUE THREAD

**Issue by wu-clan** [quick123official/quick_redis_blog#86]
先打开client，进入db界面，然后后台存储数据后，key没有实时监听刷新，或者是否加一个刷新按钮刷新key？我需要重新连接才能看到刚添加的数据

**Comment by quick123official** [comment]
<img width="523" alt="image" src="https://user-images.githubusercontent.com/58046636/162581879-55936eec-8724-4440-8456-84d0f2de3eb7.png">
这个是刷新按钮
