### ISSUE TITLE
新建页签的+点击没反应+

### ISSUE THREAD

**Issue by ex-melody** [quick123official/quick_redis_blog#88]
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAqAAAACGCAYAAAACVjjHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAACvBSURBVHhe7d0JeFTV3T/wbxJ2AYuEAiUgBCGC9gHECogCyqqQ2ooRWqssXbECoSCv1q2ItYqhBVGwtoLW+i8UaOub8BaCWKGCQI3BqthoExWCLAmENSwhyf/8zj135s7NTNbJZGby/TzPNeeeu84MmC9nuRNTUlJSDqW8XP8I+LO6arp/Y8L3JjC+N0RERDUXExNjSpXbt28funXrZtYaXsyFCxf0b3534PT30y5Hiki7XyIiIqL6EJYB1Bku7bK7rrpqsm9jw/eGiIiIGsL+/fvRtWtXs9bwYs6fP69ykW/otBfh/lmV6u7XGPG9IfLi3wciqo7qdjFT5cIugJ47d668rKxM/zKwF1WHY8eO4cyZM3q5ePEif1mEEX4WREREVBNFRUVo166dWWt4McXFxSrPeMPnkSNHcOjQIXTq1Alt27ZFmzZt0Lx5c7M7EREREVHdxJw5c8YTQD/77DPExcWhc+fOYZWSiYiIiCh6xDpbPiV89u7dm+GTiIiIiOqNDqBnz57F0aNHdctnkyZNzCYiIiIiouDTAVQmHLVv354tn0RERERU72JlBrzMdL/kkktMFRERERFR/dEtoKdPn0br1q1NFRERERFR/YmV/8hzPtkCSkREREShoFtA60Px1q344qabUFpUZGqIiIiIiEwAlXGgwVK8bRs+V8Hz8xEjcOattxBX3xObirKw9sW1yKo05xYha+2LeCPPrNanvDfw4tosdUWlWvdGRERE1LjoLvhg0C2eN9+Mz4cPR7EKnqLdD36gf1ZJB7UX8aJnCWVos8Kp99pqsQMkEREREQVdnQPo2e3b8cXIkVaL5z/+gSYdO5otQJOEBFOqhG4xzENiyo/wox+ZJSURedVtsWw3ECk/SsHAOja0Jo7yXn9UOxWIg9FcGqR7IyIiIoomtQ6gxRI8R43CZzfcgDNvvqnrumVkoFmvXros2t55pykFkoc3VNBLHOUKaRLcRqkQ+sYbao/QS0xMNCUiIiIiCrYaB9DinTux79Zb8bkEzy1bdF1Mixbo/tZbKExLQ/Hbb+s60bxPH1MKIC8PeSpsDvSX91QITEQR9Bwm3UXvCKPOdfc2CbWO7vS1/vry7S5/v62cRcjKynM9lL+yc/pu8zmn696KstZ69/O5ZyIiIqLGo0YB9KwKn4dTU3H67383NUCrESOQdOwYjv/hD56xn6L1+PGmVFvtVAg0AbTaJAy+gaKBKZ7u9BR3/7ezy3+UN/nmveENhhjlPE7OmYV2niECKUjMW2uGB1jXk/3t6zlO6UuF0Tey2qld7X1HqYBNREREFN28jW/epUYBtOXgweihQuiVJ0+iwy9+gfbz56P7P/6Bc7t34/jKlWYvS8tvfMOU6qKdCqGmWB2mRXVUoEGXEj51Xqw4LtMeAzoq0WoB9ZBz+kxUsiZIFUky9tOCG7D7Xr2QdjqwclY8ERERNR5Ww5vvUqvngMa2aYMOjz2Gjk8/rdfPbNuGNrfdpsu2VsOHm1IlpJu9KAvOvOeRp+qL2tUsgFYhT4XGdna3fgCJo0YhUQVVn955PZnI942r0LJapUTT+jkKKoV6giwRERFRY1PnWfBaWRk6v/QS+qow23XdOnR45BFcMmKE2ViZRAxUQS7vDVcYk7GTenKSs5vaGxyL8qRN0o8KgTYPWY4TJw5MQUqVM+zNPWWZRzH5CcmeyVEVtrlaT508+7XDwBRpga3p8AIiIiKi6BBTWFhYnp2djVEq7NXW3pgY9NixAy2HDDE1NSSB0/3sTWl1TBmo4ppFJvDYk3/aSTe3CnMDZRylPrbIKls7Os4lrY5SL13oa1E00B6jaY3dVBFXbR+IIp9twto/q90oa5yo6/6ku96zr+7Wt0OnCpcqvGbltbPu3XVvMs7Us2uiOTcRERFRIxOUAHp08WK0nzvXrAWHJ6y5gigRERERRbagBFAiIiIiouoKzhhQIiIiIqJqYgAlIiIiopBiACUiIiKikGIAJSIiIqKQYgAlIiIiopBiACUiIiKikGIAJSIiIqKQYgAlIiIiopCKLS8vN0UiIiIiovrHFlAiIiIiCikGUCIiIiIKKQZQIiIiIgopBlAiIiIiCikGUCIiIiIKqVoE0AKsm9oLj2eb1UCyn8CUdQVmxVB1PRbuMSt1sQePJz4B31uQuulwX9KWvdDeZt1/j0T34j5fHfh77R5yn/6u716CdT/W6w18P/Le+Lu+71LZ8dXj7zPzp+LnY/9Z836GREREFMlqEUA74I6X1wITKw8D2Rl5SB7ewSoHOzhkZyB30Y8xwCfMpWAV/on7B1UMLhJ+0nPHw9yOciOe2fUpPsuzlx14ZpjZVFMSqj33YJaJr2Db/Osr1Fshrj8e9VzXWv4yzX0/sjysXl8tVLif63H/Nvi9H+c/Iqatd1/fsayfYvaqBc/9yOfzCm73XNsVxKeuV9HTNgV/MdfevehGU0dERETRosoA6r+1sGLY04sdIgrWY4kn8LnDX10VYF1GH6TdYZ/QG1acy1+mWVut1j11v9sewHX6Hn+LvRXu3QpptTLgYdd1VZhcNAXDFj2FadPW+mx7Rd9zxRa+21f5eS/r0AI6bNEOfT0d3hz34FwPWbDzvD9rMc3xWT2q07W1LvcybMIw9U+bQKyw6vs+sTWUiIgoYhUUFJRv3ry5vCpH1k4rX/CeWXF6b2H5PWuPmBWL7Nv98WxrRW3v3uMKv4v7uGpR59P3Ied9XJX9nNde7Pt97/Fp5bW5VE2897jjmvZ7Yr92+72o4Ej52ine+wwW/f7LdaesU1fwvYZnm+Oe5N4rvQf79dRKtp/PaGH5e7pe/TyyrvyeHs7Px7pf5/7WvUm9d79QfKZERERUP6rdBd9h+HjkZlQcv+nsarfswYr5/zTlAqxbmuftXpauXEeLnNUiWDPZGa9g1cRe6LG0D3Y/MkHV+G8BlUW3sklrLGZh+NbpVhe4vy5ze5m6Xl+jJuzxk7evstb1vdld8OqnVZlinX/hHtd4S6vlVR/jqXMstbyf6+z3X7f6+l7Ds03uKSjjcatiDzmQYQ72Z+UYXtBhIl7Jexq43zkkwPuZ+rbUJqKn/iNTgNxcXUFEREQRqPpjQDsMQ3Lus77dnj5d7ZaCdc8id9oU6CGVBduQ3nMWapEzAxrwiAkyL080XbZ5WOJ3mIA15rJg6wZsU2FLgpcOhSq4PjPNPebRe86aGvCIHL8W04Y9hd2e8zkXR/B6pL/Z39Qv8u2itxcJXfr+ank/MvzAen1ybT/jS3c9hWHyDwF1P/WtYN1083lIEPaOAZ2yzkqQ6TqQu4dAePfzBOYK7DBKREREkaYGk5A64I5nxiP9fnuyyB48PmgDkp+xg6AlH+OR9pM+1oq0bgU55BSs+x9PkJmyMAO5w1QQ0S1mKgRKqFov4y93eFrOOtyx0hPq9NhIFep6qnrfVsc6jAG12WNMKyz+z61fx3zTMupaAoeumrHeK/f40iDO9q8G6/2X8Z+OIOyY1JTsCeT2uFDhrwX0APaiDxLMGhEREUUuHUDLy8v1SpUkUM7+2AStZ9F318oKrZsD7nAEUnd3t3RJ293RstSii9kOlLK8MkHlvp590Fe3mKVglZzbdH+7Q1z+x6YFVF1T2t4qtoBa+9VapS2gZh9bwXqsyFA/HcMRnItvt3Pt5C6djus+nqVbQ+1JSVZZnh4QQuq1TnFPWtOf0QOuWfFm/0AKcpHbs2clE5WIiCiQ81u34sh11+FQ7944MnQojt52G4qmTcOJefNw8okncPq551D86qs4+7//i/Nvv42SvXtRduQIUFpqzkAUXDEyCSk7OxujR482VVWQUGnGNkqI87ZaOUjoeKFnxdZPOTZjQt27fh33MGzRWiRnZKDnyxOQvhB4dEIGpuT+GGn4H8zDfLUtWbdADhumQt2Ep/W4UxknaY/Z9JJWt1o++kjP0paQFYjj3PLe3A+kSZA3r8GfgO9tNcjrS5/gPd5+vRJE9bhb1+fj3r8C9X7Le1qbMbsWeX8ykGy/B67z+V5fnhLwW/VZ5eF+zz8iboT6/6SqW+mzT8+Xa/t5ERE1LoW33oqSf//brNVMXKdOiFVLXMeOiI2Pt5b27RF72WWIadUKsW3aIOaSS/Siy61bI6ZlS5UwYswZiCqqdhe8hATdeiUB0rTUJWdYdXV/SHn16fvQ92B16yYP72K2+NMed7xs3WuazFdysFtA7cc16XGHtWiRtVR8tqfv4g1K2S98jFR7/Go9toAiV1oerc9Hwp2cV0K551FZLgEnQslSSVCuC/vP1O2rbkRf07eevdAaK5qOpx3vh7q/3PGY4Umb7I4nIgqV0kOHULJnD85t2oTi117D6aVLcfLRR3H8vvtQNH06jqak6IBbMHw4Dl9zjW5lPdi1Kw4mJOBgt2442L27Xg5dcQUO9eqlW2KP33svzqxYoVtmywoLzZWoMamyBVSeWSktiJW1yMlEE93lLd3QEq7quwVUeFrR5B6drWHe1kjnPcs9zlOhJvXj631aP619at+iJiGqYmtqAM6JP45WXH/q2gJa5T057kX2r98WUJcanc/x2TjeM09rLhERVUmC3om5c3WYDEdNv/51NBs0CE0HDECz/v0Rd/nlZgtFq5p3wUcldukSEVH0Ky8uRllREcqOH0f5yZMoO3HCW1Y/y44d0y2SpUeOoEyF1dIvvzRHhlaTHj3QtF8/NOnbF01790YTtcR162a2UjRgACUiIiL/yst1ILWDqf4py9GjVmA9fdoKr2opP3XKqpNAe+YMUFZmThIcsR06oNk111ihNClJh1JZKDIxgBIRETUSEg5l4lBMs2ampp7JU3bMUm4Caelnn6Hk449x8aOPcGHPHlzYsUPX10Zs27ZoNW0aWt5+O5r0lIcsUqRgACUiImoETtx/P4r/9Cc0SUzEpc88o8dchoPyc+f0JKcSlUUuZGXh/LZteqhATbW8804dRJvfcIOpoXDGAEpEESdL/ZJy69evHy5cuICSkhJTQw2hadOmaNasGZo0aaLXi1WQKC0tRVmQu2PJKzY2FnFxcWjVqpVev3jxYoW/CxfT03HhgQfMmvqcfvADNJ0zx6yFhvvPRmUu5uSgRC3y8+Levbjw3nu62786WqakoO1DD+nHRVH4YgAloojjL4D26WN9A5v8kqOGY4ceOwydOnUKLVu2rFbooNqRL5M5ffo02rRpo9cl9Av774K0MB6fMAGludZXIIvWjz+OFnffbdZCw/1no6ZKv/jCCqWffGKF0j17ULpvn9nqq/mIEWi3ahVi+P+DsFWDr+IkIgpf8suN4bPhyWfgbHmTlk+Gz/oVExPj08Ls/rtw9rnnfMKnaKYCWqi5/2zUlDyaqcWYMWh93334yvLl+OqOHfpn8+HDzR5e5996CydSU80ahSMGUCIioihV+umnKH7+ebNmaTV/PmK7djVrka3lN7+Jy157De3Xr0erSZNMreXs66/jwu7dZo3CDQMoERFRlDq3erUpWZpecw1azZhh1qKHTKi6dPFitLjlFlNjOb9liylRuGEAJSIiikIyk/z8unVmzdLyRz8ypejUavJkU7Kc/dvfTInCTSxnJhIREUWfix9+qB8Qb2vSrx+ajR1r1qJT85EjfWa/lx44gHD9+tHGji2gREREUUhmijtJ93tj0PTKK03JUvr556ZE4YQBlIiIKApJC6iTfIVlY9CkVy9TslxkAA1LDKBERERR6KLreblxjSSAxvXoYUoWeX4ohR8GUCIioihUdviwKVnirrjClKJbXEKCKVlK9+83JQonDKBERERRqPzsWVOyNJZvBYrr3NmULBcDfFsSNSwGUCIioihT7vrGoZiWLeUrk8xadIvr0sWULO5vgaLwwABKREQUbc6dMwVLTIsWplQzx44d00skib30UlOylJ04Id8Ja9YoXDCAEhERRRl3CyiaNTOFmnnuuef0EklKjxwxJUucfO1oLONOuOEnQkTksOeFq5C6odCseRVuSMVVL+wxaxRxPgV6LQWWmdURqjziTbMSjS5eNAWjeXNTiH5lBQWmZIn72tdMicIJAygRURTLz8/XSyBVbY9Wb81Wy81mJcj279+vl0Cq2h4U7hY/dyCNYuffesuULO5JSRQeGECJiKJYQkICcnJysHnzZlPjJXWyTfah4Onatat+XzMzM02Nl9TJNtmnXjVpYgpGIwmgFz/9FKcWLTJrlubDhpkShRMGUCKiWinEhp9dhauuspdUbHB85bTdZS9d+tb230I68HW9Ocbd1e/cZu8fDCNHjkRxcTF27NhhaqDLUifbwt6bQOdlwNTfqZ/OrnOpV+v2MvVTU29IN7u9bYTvM9kxVZ3Pcx7TPe/ZNwhd86NGjcKZM2ewfft2UwNdljrZVt9i4uJMySgtNYXADrueG1qZmuwbSmdeeMGULE1690bLlBSzRuEk9osvvkDhl3lmlYiINs8f7giC1jJ8vrMFUcLncMzv/Ro++ugja/l/fTB/pCs0LrsLu4ZY21+b+SzuUud5Ag+b/Wep66z37C/hc/iW0dhqzrd10ce4K4hjTm+66Sbk5ubiww8/1IuUpS5ilAGf9wQO2l3nEj4/AH6u1qXu4NeBTRuBndbeOnxC1eltauleAJy2NlUwVR3XxbHvRFNfVxLu//vf/+KDDz7Qi5RDFvhdAbT8wgVTCmzbtm14/PHHfZatW7fqxV0v+4abk+q+itesMWuWNnPmNJrHT0Wa2Msvvxxxp0+ZVSIiGr1oqzdYegLhaLNVObQLmzfNwms/6W8qlH4TsWjss9j1vlkXM1/Dj/tZxf5DZqn/zsLU8fFWRb9Bau1jHNCtpoXYtWUzZk0ZD7MV8eOnYtayXUFrBW3bti1GjBihg4MsUpa6iBELPOUYs7ksF2jdUb3FZh1q21j14wVpBVXhNMe1/8vj1P6m7M8Bx8TpmUEaGyrvr4R8O8RJOWTvubsLvhotoJHs5IIFOPPii2bN0uKWW9AiOdmsUbhRf0VP4tS5lmaViIiqdDgfm8cmwHfkZDy69AY+zq84g17rmIDRFY6x5SN/E/Dsd52trnfhWU9ADY5SFULKysr0IuVIlnUOOH3Y220uyyZpJd0P7JQw2QIYbO1apZdVih1aYM7zO1MZJA31nsfIY5ccIbS8uLjKVtBhw4bh0Ucf9VmGDx+uF3e97BsudPj8ne8H17RPH1y6eLFZo3AUi4uHcSougv4VTETU0CRMblKh0aw69Umw2zBrQgXTsaOxaItvq+tHHy3B+E5mlzoqKirCm2++qVvhZJGy1EWqgSpgJjm6ze1FuucHf1XtoAKq3R2vqWAaqAteSAiV43+uysEKofL+btmyBTfffLNepBzK9zy2k+8fnvIqHijfsWNHU6paTfatT4HC51defBGxkdTC3wjForAAZa35IRERVVunQRg99lnfMZrv/xZ3LZuFQabLvWbiMWgkMH/RBgRoP60zmX3tHNMqi79Z2pFiZk8g5wPvcz19dAValwEPOCYTTf3IFPwY4cgv32hjCkGwceNGXH311T6L1IVKbIcOpmQpi+B/cPhz8he/CBg+m/ToYWooXMWePlyE5m3ZBU9EVH3xGP/rrVj0yV3eQPdd4LWPfgzHqNAaiR+/BK/1no/hjoAYrAffb9q0Ce3bt8egQYNMDXRZ6mRbRLoZ+GtH4ElHF7zMlNetnr2AT28FDqiAam/DVYHHgHY/593v2wXqvD80G+pAgmZ8fDwGD/YOBJCy1IUqhMaqazmVR0kAvZiXh2N33YUzv/+9qbEwfEaWmHf+uKr8k8u64J5bHAPsiYjCWFaW65k6yhVXXIFWrVqZNbLZD5kP9KzPqrbXhjze6VLzfdwnTpzwlBsL+yHzgZ71WdX22nC+z1KWvwunH3gA5xyzwts+/zya3aqSeTWdPHkSS5Ys0eXU1NSgTKBy/tmojfNbtuD43LkoK/TtK2D4jDyxh8+3R1vXZDkiIooOEiwrC5dVbaeak2BZWbisanuwuMeAur8jvSoSOO+77z69hMMTE6TF89iUKRXCZ7MhQxg+I1BsUcuvIlrbDMaPH4+kpCTPMm7cOLz77rtma81kL/eex3dZgWy1vTBjJpKWS8k/fXwl2/3R55ydXm9jwvzxeR2H0jEzaSbSgzgLl4iIQiPWNVGovBYPj7/sssv00pDKS0pw4sEH9ZhPt0umTUP7NWsYPiNQbIz6F1K0PqJVHvr76quv6q89kyUlJQUzZszQY552797ts8i+lRlwr3WOnJztSBsHpK6x12dggNmnMvr4e6uzp1f8hGXIWZrseS5gyHVKxrKcZUgO0ixcJwnkMzNCGa2JiBqX2K/K4wC8Sr/80pQiR8nHH+PY5MkoVr/L3douXKiXCt97TxEhtn+vxjMB6fvf/z4eeugh/PGPf8SyZct8lgULFpi9iIiIIp+7BbTswAFTigzn/v53HP3mN3Fh1y5TY4lTr+syFUil9ZMiV2znZqYUYunp6X66s60lIyPD7BV83/rWt3SrqHOZOdPzXRp15uyqd7bwubvofbr0A3Wz71nhs61ax6ja9NmO/cwQgYDkGo593zHVlmyscHTBW68h3Zzfrnddzz3MwOf8SVixx9p/8lIgc+5QVefo4nft63sucy8ZZp/l/9DnWeEzSdg6N1tWiYgqBtDSfftMKfydXr4cRT/8IcrPnjU1luY334z2f/0rmkfS18iSXw3Wbp2cnKxbI90efvhhTJgwwawFx3e+8x3fYONa7r77bt0NL2UZN1prSydj5/Wma35NqgpYC/yPn1RBa3JOGraboQHbp1VjAkB1jzn0DvJHbzfDA2S4wBKsDBTIJPBNAlabc+ZsTVD3XMVzAZeq7Q/K/tI1L4FvKDKd18uZ7A2FFc6fhgTEI3lpDlbPBsYsluNMF7/edy/Stpp9zbl8w2Qm5u0bbG2/9yYMGT0GS3Y4Qqp67ZkbUzF9QoMNWiAiChvyHFD9jUhGWUFBhUAXbspPncLxn/0Mp5580tR4XfLjH+OyP/wBcd26mRqKZA06cOKee+7RYzJtUpYwGGyFhYUm1FS+zJkzB4mJieaoWpi9GjPshwD2T1HhLxP5gSbwbMyXL+bQ4vsPqN44z+oc0ykZMzwBLF6HtMx99lG+sncsUSEwxTuGVR372OIxZiWA2dO9Y0IrBD4VLqelmlCowumqJUhd4xgjq86fHOAhida9POYYb2qdK3PzO46W3jFIu907jjZ+wnSkLl3pbaF9NxOZswdXa0wuEVFjEOsKa2W1mIgUKiXvv4+jkybh7J//bGq8Ln36abR95BGzRtGgwUfuyrPFvv3tb+tFysEmXzd32223mbXKSXd8fQTgCvrPQM4aYLJuga3mLPMaHOPsqh8asEWzEPk5QN9afW2gcSgfmVhi7sksk5YAOfnq7PuRv3EMEqo1gSnAvXRKwBhH6K5oAAbPVqHzXYmohXhnM3wCKhFRYxfXpYspWUo//9yUwkfZkSM4+cQTKBw/HiX//reptcRdfrme5d7qrrtMDUWLsJg69tRTT+mlPmzYsAF33nmnWQvs9ddfR48ePXDdddeZmnomgVJaXreOQebwGoTQKo6R8Lmym90lnoPtAVs045GQBOzN9+2e37+vBl/NJwFxnHdYgGfRM/e7IqGyFmAf/u9FG5cg36oX0IDrTSuptMZiDIbUw4x9IqJI1aS/b7fT2RUrUPKvf5m1hnfmpZdwZOhQnHnhBVPj1eKWW9B+/Xo0U9sp+kT9swv6q798X3U9isKfVatWYeLEiWatfhVmrPCGRxXi+ppiZap3jLslUVoFAwfKrt1UkJ271jtJ6VA6VspX1lVXpyEq8s3DAr9jTK3u/yWTHJOg1PnTA3yzoA6SPmNmC5H+q3nA6CHqTJWQoQ4qei5Q+/ad1oCPrCIiCkPNXJN1Snbvxok778TJH/wA5/74R5Tm5Zkt9U8eIF/6zjv6+9uPz5mDgmHDcPKxx/yOS209axbaqf3iXA/Tp+gR9QE0MzPT2z1cyRIXF6eHAYRCfAIwb7h97cnAmqqftVm9Y8wYzEn2fguQnxR4TKc8Z3T74r3eLvRfAdOrGgPqQyYUrUZfPZvdvqZ3ZnqF8w9XYdjc84Db0wDnLHg9xKCv4zVak5uWVTmhSIKu+pw3pmJwbb+Em4goSjXp1w8tp083a14XtmzB6UceQdHIkTiufvcV//rXOPfnP6Nk586gPa6p7MsvcT4jA2cWLkTR2LE49o1v4LwKvicXLMDZtWv1d7q7NRs0CJe98grazJ9vaihaxRw+fLj8/fffx+jR0fdd8DKzvSZC1v1OQSWPhxq6b3qNH/RPkYvfBR/eGvt3wTcEf98F71T89NMo9tPNHUhMy5aI69ULsV266HGk8kgne9GtkjK7Pi4OaNoUMU2a6HX5WfLuuzrElmzdipL33jNnq5o827P13Llo9d3vmhqKdlEdQKkRkK8LHZ6JMVvr5xubKDwxgIY3BtDQqyqAigtvvomzv/2t7oYPF7Hx8Wh1zz1o/cMfIqZNG1NLjQEDKEUo6xmk8zZaX4vqefwVNQr+AmivXr1QXl5u1qghxcTEeD6LZs2aoWXLxvONew3l7NmzuHDhgi47339/yvPzUbpzJ0q3b0dpZg0mntZVXBxir7kGsVdfjdikJMRKC+uVV5qN1NgwgBJRxPEXQAcOHGhKRFRd8uD3kr17UfLBByj94gs9LvPip58G7Xvjm48cqcd1NlN/P5tde63VbU+kMIASUcRhACWqX2XHj+sQKg+uLz10yPqp1ksPHNDruHAB5RcvovzcOatcUoLy8+f1+NAWY8boRyc1Vwu71SkQBlAiijgMoEREkS3qH8NEREREROGFAZSIiIiIQooBlIiIiIhCKrasrAyyEBERERGFAltAiYiIiCikGECJiIiIKKQYQImIiIgopBhAiYiIiCikGECJiIiIKKQYQImIiIgopBhAiYiIiCikGECJiIiIKKQYQOtg9+7dSEpK8llmzJiBo0ePmj1CIRsrkmYi/ZBZrRbfY7KXq3tfnm2tEBEREdWzmIMHD5a///77GDt2rKmKLhkZGZgwYYJZCy4JoHfffTdycnJMDfDwww/jk08+wbx580yNr+uuu86UgkXC5EokbF2G5E6mqkq1OaY2QnUdamyysrJMyWvgwIGmRJGi81Lr58HZ1s/6cuLECRQWFqK0tNTUEFFDi/oAKq2SEgolKAabvwAqfvOb3+C9994za75mzpwZ5BDKAEqNDwNodAhVAM3NzUWXLl3QokULU0NEDa1RdME/8cQTWLJkiVmrf3PmzMGrr75aYalKYcZMR3f+ChXfhIQ4Vxf7nhVImp2OQrNqkf3sY91d8oVIn21vS8LMjHxTb9HX9XTBm+tlqGvI/na9XDPg+dVR0o3v2a7u/VA6ZiZNxhJkYt5wVee4X9/XKffjfSXWvaSb+1XX2eLntep7sd8fIqLKScsnwydReGk0Y0BXrFiBBx54wKyFIRXYFszti9U5ObpFNWfNYLOhOiTk7cRgz7F91bod0CR8DkXm6O3WNrVM3zdPBcPKqPPtG2ztf+8AK/BNguPe1Pl/5Q2FEj4nY7Xn/NsXJwCdkrEsZzVSMQZpW1X90mTEq30lYA51vk61T9+5Q7Fij3UubWkm8KBsW4bkkYORujET7zgCb/aOJRizOAXqzoiIiCgCcRJSWNmLfDto9R9Qg4AlIW+Gd//+KUgbtwQ7JdQdegeZG1MxfYLEP8uAeyUYVkad73bv1SsEPjm/Cqk6FKrgvHJpKlZLUDXiJyQHuPdCvLM5E6lrHPeqSimLx2DJDkd75uzpji572Q7M+4u3hXbn0jEYc6339RAREVFkaTQBVGanP/XUU2YtDEmL4dYxyJTu6qQk3xbBGotHQpIpHspH5rgEdDWrNVeI/Bwgc+5QT5d5UtJQzNuYaYXlGp1/P/I3jkGCazxofEJfICfft5vdIf5aFTiX7rRadPfsxBKfgEpERESRplEE0IceegipqZW3+YUF3W1tdUtjUl1CqBUatU4JGLMxX0U/BxUa95pi1awwm7rG7jL3LjP6q83+zh9QVySMM8HVLSlBd9H71WkIxpgWXWmNTb3ef/sqERERRYaoD6BpaWm45557zFoY27PCETglqJmiCW2Z73pGXGLFJPcIzkxHF7WMs1yAeUhDigmIfbEEKx0TfbL/Mk8dUX0Drk/FkkkBJv2YcDjZ8RzRwox0//uqiDlk9BjXuazXU3mojEfyNHUPq2ZiZY55XURERBSxoj6AJicnm1L98XZNV77IY5sCUkFx7yR7X2vSkG5hlPD1YBrg6QLficFr3K25Y5DWbafZnmRN8jGTfmQM5Qwz0cfevvP6qsaAuvSfge2L92KyOV4vnpnp6v6WbkdazmTPtqGbJTYLM37TMQs+fsIy17kmA2tMa2pl+luTkTB6iHldREREFKmi/jmg9a3SUOlH8B9E31jI46H4TFGy8Dmg0SFUzwGVLwfp3bu3WSOicMBZ8HUkgbImC9VO9vLJnHxEREQN5rPPPsNtt92G9PR0U+NLvoDmsccew7lz57B8+XJPr6Aszi+nkfP87Gc/w/Hjx01N48QASuHNPAB/ck4atjse9URERBQqEhblS23mz5+Pd999VwdMIWHymWee0aHT6d5779WTdf/0pz/hhhtuwNe+9jUdTuX32bhx47BhwwYMGjRIr0uolfP44y+sSgCu7JhIwQBK4a3/DGvWvWdMKxERUehI+Js7dy5++tOfYujQoViwYIGut1s7A5GA+Pzzz+uvA+/UqZM+Tn6fbdy4EePHj8euXbv00rNnT3NE1aQl9W9/+xteeeUV9OjRw9RGJgZQIiIiIj8kREr4lBB5zTXXmFqrhbNjx47IyMgwNb4ktC5btkwfJ0FRWi3t7nhnC6gsUpY6u1U1EGeg/cpXvmJqIxcDKBFRHYxYCkz91CrvXA10/p1VDuhNa/KNvSwz1R5mu12/TJ3Ps7+q3GnqNXXdXvY2tYxQxzr5HOvnvuTe7e291L1r5pz2ayJqrKR1c926dbjyyit1QLQDpL0MHjwYd9xxh9nb1z//+U9PsJR9u3Tp4nmGtrsFVMpSJ6E2EHegdZJWUfue7K55uXdpoXWOPbXrAo1hDTUGUCKiUJFw9wEw9lZr5vdfOwJPukLlCLN9pipLoH3ynNpP7Sv7/7wF8G1HkBzxf0CXr1vbDqpjDqhj7eAo4fNJ9VNvk2NV2RMylanqugfU9e3tXQ6bANtL3aY656aNrrBL1Mi0aNEC999/vw6gs2fP9gRIeXLQ5MmTzV7+ySMg7f3l2LNnz/odAypLbm6uOcq/EydOYOHChfje977nN3xKq6gEWbmWXOPll1/W26699lrs3On9W3zw4EGcOnUKN954o6lpWAygREQhsjMLON0KeFmFPDFY/Q5LKgNeMKFRAmeOY/u/TgGtO6j9rFXMlKFiKpDqXynqmAPqx8SbZUVRxwxV/0f/3Hwt2fpiFWRHWGUxU8oqZNotq5+r6w51PLlqorrugSNmRZ3TeV9E5Kt169Zo166dWatIutOlpVFaHc+cOaMnIfkbAyrrr7/+erXGczrDpE3qvvWtb3m65Pv27avvTcKmBM3//ve/nslKH374Ia644oqw6b5nACUiqgFpOazQbe2iu+LNPs6u7xcKVLBzzTeQ4LfdPNbUvV0C52lHaFyW6wikJnA+a9+DCovbVWj0BFI3tX8X9SPLhEq57qa3rLKQwOoOpPZ9EZGXhEoJeJWR7nmZLS/hT/aNiYnB97///QotoHbXeWXd4pdeeil++ctf4vDhwz7jROU+pG7evHme8/Tr1w+///3vUVRUpIOmBE4JnrLvf/7zH9xyyy3m6IbHAEpEVE0SPrerAGh3W886BeSYbR4qyN2tftj7jD0XOKi6Satkd+trxCwqTB78OvCkCbPPtlE509Hz9/JMFRpVaNVB9//U/ajrSde9cAdM3bpqymLmD61ueTsod7/V2/IqvqGudVq9PiKy2BOJJDhKsKus1TIxMVF3d8skJdm3e/fueOmll/y2gMpS1bc2ynCAOXPm6C/hsMOq1MlEKHnUk30ee7EnTDmDsOjcubP+GQ4YQImIqsO0MM5yBEAJcUmm7KGCn09IvEoFORUSqzuecqAjBOqW1FxvmH1V1TknIskkIozzbl+v1u2JSHJvEn7tgCmh2HmvEqbX9/Qei42+QXnwV9V/7O5+IvIZ1zl9+nT9/E8h40QlDDpJ66OM2Xz77bd1q6MdXmXx1wJaned6yjllEpK0cNqTiyRgyhhQ53NCnewu+bS0NIwcObLCfTakmPr6Kk75Hx4RkdABJ4ga5Ks4ZXb6R8BfZ5oucENCoN16KIHx26fU61Xhz0MF114q3L2qjntBhb7PVSB9y9FNLpOFJAhKnZxronqv7FZM57ltEhwldP5EvQUVriX3KIHVWWeT+7BbSf29Fsd96roArzeY7N8Twf7z4cav4qS6kPC4f/9+n1nqEhZlVvqjjz7qGVMpoVDGcz744IN6/Ve/+hVWr7b+VScTkezj/R0bSKDrfOc739GhUkKx3J90w9tkgpTcgx02Zbs8O3Tx4sVVXi+U2AJKRFQdXYHWZcC/zKqmQptMBKrUfuC0KQ5Uvw88E30MGXvp7Ha3x2gGmz0Byg631aLut77CJ1GkuPrqq7Fp0yZPa6XdinnTTTfpsZbSeil1Egpl5rmQ8CllaS2VRj4Zq+k81t0CKou/54BKN/+vf/1rn+Ao3etyXrvb3tkyK4tMdnK3dMo/0MMpfAoGUCKi6jCTeDyTfpRlb3nDpYcKlM5naMpjlZKusoKcPRPd+dzQHPV/4Z+YFs7uqmzPYhf+xnFuUj9l/8EDVSD2dy3XJCdN7XO3uq5nVryZ5f6A6a4XUzeq/zhm3OsJT23MClEjJiFQWjadIU8WCX7ubVIn4U9CoB0Q7XXnsf6Wyp4DWlvSgiqtn+E0+cgC/H8hbTKhFLE05wAAAABJRU5ErkJggg==

**Comment by quick123official** [comment]
2.7.1 会去掉“新建页签的+”。这个按钮没啥用。

**Comment by quick123official** [comment]
等待2.7.1发布版本哈
