### ISSUE TITLE
集群连接 报 cannot get db size

### ISSUE THREAD

**Issue by leohapps** [quick123official/quick_redis_blog#9]
如题，连接成功，但是UI窗口空白，弹出“cannot get db size”

**Comment by quick123official** [comment]
请提供一个截图

**Comment by pawel-b** [comment]
I have the same issue.
![2020-10-02_08-49](https://user-images.githubusercontent.com/5254491/94895671-2c4b5880-048c-11eb-9f2e-6593acfc0eb6.png)

**Comment by quick123official** [comment]
> I have the same issue.
> ![2020-10-02_08-49](https://user-images.githubusercontent.com/5254491/94895671-2c4b5880-048c-11eb-9f2e-6593acfc0eb6.png)


Which version? Can you provide the log information?

mac log file: /Users/${User Directory}/Library/ApplicationSupport/QuickRedis/logs/info.log 

windows log file: C:\Users\${User Directory}\AppData\Roaming\QuickRedis\logs\info.log

**Comment by quick123official** [comment]
这种情况一般是所在机器无法连接到redis集群。
