### ISSUE TITLE
数据库多显示问题

### ISSUE THREAD

**Issue by nuo010** [quick123official/quick_redis_blog#92]
实际项目只有10个数据库当是软件还是显示16个数据库
当点击不存在的数据库时会报错
![image-20220330130351217](https://gitee.com/ak47-b/blogs/raw/master/images/image-20220330130351217.png)

**Comment by quick123official** [comment]
使用的版本是哪个？

**Comment by quick123official** [comment]
可以升级到最新版本。

**Comment by nuo010** [comment]
![image-20220330143454195](https://gitee.com/ak47-b/blogs/raw/master/images/image-20220330143454195.png)
2.50 版本 我先试试吧 就是目录管理哪个地方用起来有bug 我先用用在具体说吧
