### ISSUE TITLE
新建key bug

### ISSUE THREAD

**Issue by nuo010** [quick123official/quick_redis_blog#94]
![image](https://user-images.githubusercontent.com/68454615/161414014-1322f6f9-fa6a-49c8-8756-efe36519f8f6.png)
手动创建key为什么会这样??

**Comment by quick123official** [comment]
更新到最新版本试试。2.6.2

**Comment by nuo010** [comment]
还有老哥能不能出个刷新的按钮  每次都关闭再打开浪费时间

**Comment by quick123official** [comment]
下载2.7.0版本试试
