### ISSUE TITLE
d

### ISSUE THREAD

**Issue by leozz705** [quick123official/quick_redis_blog#97]
操作系统
 Mac 蒙特雷12.3

QuickRedis 版本
2.6.2

问题描述
请问下这个可以部署在centos7上么，怎么运行？

**Comment by quick123official** [comment]
这个是pc客户端工具，在本地运行，不需要部署到服务器。

**Comment by leozz705** [comment]
我这本地连redis好麻烦的，可以部到服务器上的话能省事不少。不知可否打包运行在服务器上呢 @[quick123official](https://github.com/quick123official)

**Comment by quick123official** [comment]
这个桌面应用的设计跟bs结构差别有点大，不支持的
