### ISSUE TITLE
能不能添加一个全部删除的按钮，还有就是数据库显示key数量的地方，当key删除后刷新不管用

### ISSUE THREAD

**Issue by nuo010** [quick123official/quick_redis_blog#98]
操作系统
Windows or Linux or Mac

QuickRedis 版本
例子：2.6.2

问题描述
提供复现BUG的步骤或者BUG截图
![image](https://user-images.githubusercontent.com/68454615/167347637-f1fad0e9-395a-42c1-9de5-fffb61d5ef3a.png)

![](https://qiniu.ligl.top/20220509134508.png)

**Comment by quick123official** [comment]
1. 全部删除是指删除当前db全部的数据吗？ 这种操作建议使用命令进行，避免误操作。
2. 数据库显示key数量的地方是一个BUG，后续修复。
